/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;


import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.opencsv.CSVReader;
import controle.ContatoControl;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelos.Contato;
import modelos.Endereco;
import modelos.Telefone;
import pdf.PDF;
import persistencia.ContatoDao;

/**
 *
 * @author liass
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
        //carrega os contatos na tabela assim que o programa inicia
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_Resposta.getModel();
            model.setRowCount(0);

            ContatoDao dao = new ContatoDao();
            ContatoControl contatoControl = new ContatoControl(dao);
            LinkedList<Contato> contatos = contatoControl.listar();

            for (Contato contato : contatos) {
                Object[] rowData = {
                    contato.getId(),
                    contato.getNome(),
                    contato.getTelefone().imprimirCelular(),
                    contato.getEmail(),
                    contato.getEndereco().imprimirEndereco()
                };
                model.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar contatos: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Resposta = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_Nome = new javax.swing.JTextField();
        jTextField3_Email = new javax.swing.JTextField();
        jFormattedTextField1_Telefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_Incluir = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_Listar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jButton6_PDF = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton_Consultar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1_consultar = new javax.swing.JFormattedTextField();
        jButton_ordenar = new javax.swing.JButton();
        jComboBox_Ordenar = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4_Logradouro = new javax.swing.JTextField();
        jTextField5_Numero = new javax.swing.JTextField();
        jTextField6_Complemento = new javax.swing.JTextField();
        jFormattedTextField2_Cep = new javax.swing.JFormattedTextField();
        jTextField8_Cidade = new javax.swing.JTextField();
        jTextField9_Estado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Contatos Esmeraldina");

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone:");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Endereço:");

        jTable_Resposta.setForeground(new java.awt.Color(0, 51, 0));
        jTable_Resposta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "E-mail", "Endereço"
            }
        ));
        jTable_Resposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_RespostaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Resposta);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail:");

        jTextField1_Nome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        jTextField3_Email.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        try {
            jFormattedTextField1_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_Telefone.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jLabel6.setText("AC Esmeraldina");

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jButton_Incluir.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jButton_Incluir.setForeground(new java.awt.Color(0, 51, 0));
        jButton_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-button_11519998.png"))); // NOI18N
        jButton_Incluir.setText("Incluir");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        jButton_Alterar.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jButton_Alterar.setForeground(new java.awt.Color(0, 51, 0));
        jButton_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_8528524.png"))); // NOI18N
        jButton_Alterar.setText("Alterar");
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });

        jButton_Listar.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jButton_Listar.setForeground(new java.awt.Color(0, 51, 0));
        jButton_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file_14361687.png"))); // NOI18N
        jButton_Listar.setText("Listar");
        jButton_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarActionPerformed(evt);
            }
        });

        jButton_Excluir.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jButton_Excluir.setForeground(new java.awt.Color(0, 51, 0));
        jButton_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_13901891.png"))); // NOI18N
        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jButton6_PDF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6_PDF.setForeground(new java.awt.Color(0, 51, 0));
        jButton6_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pdf_4726010.png"))); // NOI18N
        jButton6_PDF.setText("PDF");
        jButton6_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_PDFActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar:");

        jButton_Consultar.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jButton_Consultar.setForeground(new java.awt.Color(0, 51, 0));
        jButton_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_4315632.png"))); // NOI18N
        jButton_Consultar.setText("Consultar");
        jButton_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultarActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celular", "Email" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        try {
            jFormattedTextField1_consultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_consultar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jFormattedTextField1_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Consultar)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextField1_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );

        jButton_ordenar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jButton_ordenar.setForeground(new java.awt.Color(0, 51, 0));
        jButton_ordenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ordenar.png"))); // NOI18N
        jButton_ordenar.setText("Ordenar");
        jButton_ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ordenarActionPerformed(evt);
            }
        });

        jComboBox_Ordenar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jComboBox_Ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celular", "ID", "Email" }));
        jComboBox_Ordenar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_OrdenarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6_PDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_ordenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Ordenar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_Ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logradouro:");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("N°:");

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Complemento:");

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CEP:");

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cidade:");

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estado:");

        jPanel4.setBackground(new java.awt.Color(0, 51, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel4.setForeground(new java.awt.Color(0, 51, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sobre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField4_Logradouro.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        jTextField5_Numero.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jTextField5_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5_NumeroActionPerformed(evt);
            }
        });

        jTextField6_Complemento.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        try {
            jFormattedTextField2_Cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2_Cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2_CepActionPerformed(evt);
            }
        });

        jTextField8_Cidade.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jTextField8_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8_CidadeActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mengao.jpg"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField3_Email, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1_Nome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFormattedTextField1_Telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel10))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField5_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField6_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextField2_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField8_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jTextField9_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addComponent(jFormattedTextField1_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField2_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8_CidadeActionPerformed

    private void jFormattedTextField2_CepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2_CepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2_CepActionPerformed

    private void jTextField5_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_NumeroActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        String message = "Desenvolvido por:\n" +
        "- Luiz Iassuo\n" +
        "- Samuel André\n" +
        "Copyright 2024 Japa&Portuga";
        JOptionPane.showMessageDialog(this, message, "Informações de Desenvolvimento", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jComboBox_OrdenarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_OrdenarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_OrdenarItemStateChanged

    private void jButton_ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ordenarActionPerformed
        try {
        //inicializa a tabela
        DefaultTableModel model = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Nome", "Telefone", "Email", "Endereco"}
        );
        jTable_Resposta.setModel(model);

        //faz a recuperacao dos contatos
        ContatoDao dao = new ContatoDao();
        ContatoControl contatoControl = new ContatoControl(dao);
        LinkedList<Contato> contatosList = contatoControl.listar();

        // converte a lista encadeada em vetor
        Vector<Contato> contatos = new Vector<>(contatosList);

        //ordena 
        String criterioOrdenacao = (String) jComboBox_Ordenar.getSelectedItem();
        switch (criterioOrdenacao) {
            case "ID":
                contatos.sort(Comparator.comparingInt(Contato::getId));
                break;
            case "Celular":
                contatos.sort(Comparator.comparing(contato -> {
                    Telefone telefone = contato.getTelefone();
                    return String.format("%03d%03d%08d", telefone.getDdi(), telefone.getDdd(), telefone.getNumero());
                }));
                break;
            case "Email":
                contatos.sort(Comparator.comparing(Contato::getEmail, String.CASE_INSENSITIVE_ORDER));
                break;
            default:
                break;
        }

        //limpa a tabela
        model.setRowCount(0);

        //adiciona os contasto na tabela
        for (Contato contato : contatos) {
            String telefone = String.format("+%d (%d) %d",
                contato.getTelefone().getDdi(),
                contato.getTelefone().getDdd(),
                contato.getTelefone().getNumero()
            );
            String endereco = String.format("%s, %d, %s, %s, %s, %s",
                contato.getEndereco().getLogradouro(),
                contato.getEndereco().getNumero(),
                contato.getEndereco().getComplemento(),
                contato.getEndereco().getCep(),
                contato.getEndereco().getCidade(),
                contato.getEndereco().getEstado()
            );

            model.addRow(new Object[]{
                contato.getId(),
                contato.getNome(),
                telefone,
                contato.getEmail(),
                endereco
            });
        }
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage());
    }
    }//GEN-LAST:event_jButton_ordenarActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String selectedItem = (String) jComboBox1.getSelectedItem();
            try {
                if ("Celular".equals(selectedItem)) {
                    MaskFormatter celularMask = new MaskFormatter("+## (##) #####-####");

                    jFormattedTextField1_consultar.setFormatterFactory(new DefaultFormatterFactory(celularMask));
                } else if ("Email".equals(selectedItem)) {
                    jFormattedTextField1_consultar.setFormatterFactory(null);
                    jFormattedTextField1_consultar.setText(""); 
                }
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultarActionPerformed
        try{
            ContatoDao dao = new ContatoDao();
            ContatoControl contatoControl = new ContatoControl(dao);

            Contato contato = contatoControl.consultar(jFormattedTextField1_consultar.getText());

            DefaultTableModel model = (DefaultTableModel) jTable_Resposta.getModel();
            model.setRowCount(0);

            model.addRow(new Object[]{
                contato.getId(),
                contato.getNome(),
                contato.getTelefone().imprimirCelular(),
                contato.getEmail(),
                contato.getEndereco().imprimirEndereco(),
            });

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Contato não encontrado: " + jFormattedTextField1_consultar.getText(), "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Erro ao ler o arquivo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

    }//GEN-LAST:event_jButton_ConsultarActionPerformed

    private void jButton6_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_PDFActionPerformed
        String pdfFile = "contato.pdf";
        PDF pdf = new PDF();

        try {
            ArrayList<Contato> contatos = pdf.recuperarContatosDoBanco();
            pdf.gerarPDF(contatos, pdfFile);

            //abrir pdf no leitor padrao
            pdf.abrirPdf(pdfFile);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6_PDFActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_Resposta.getModel();
            int selectedRowIndex = jTable_Resposta.getSelectedRow();

            if (selectedRowIndex != -1) {
                //mostra uma caixa para confirmar exclusao do contato
                int resposta = JOptionPane.showConfirmDialog(this,
                    "Você tem certeza que quer excluir este contato?",
                    "Confirmação de Exclusão",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

                //pede a confirmação da exclusao
                if (resposta == JOptionPane.YES_OPTION) {
                    //converte o ID para int
                    int id = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
                    ContatoDao dao = new ContatoDao();
                    ContatoControl contatoControl = new ContatoControl(dao);

                    contatoControl.excluir(id);

                    model.removeRow(selectedRowIndex);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Selecione um contato para excluir (Para isso, liste e selecione o contato a excluir. Caso não encontre, use a busca).",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListarActionPerformed
        try {
            DefaultTableModel model = new DefaultTableModel(
                new Object[][] {},
                new String[] {"ID", "Nome", "Telefone", "Email", "Endereco"}
            );
            jTable_Resposta.setModel(model);

            ContatoDao dao = new ContatoDao();
            ContatoControl contatoControl = new ContatoControl(dao);
            LinkedList<Contato> contatos = contatoControl.listar();

            for (Contato contato : contatos) {
                Object[] rowData = {
                    String.valueOf(contato.getId()),
                    contato.getNome(),
                    contato.getTelefone().imprimirCelular(),
                    contato.getEmail(),
                    contato.getEndereco().imprimirEndereco()
                };
                model.addRow(rowData);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButton_ListarActionPerformed

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_Resposta.getModel();
            int selectedRowIndex = jTable_Resposta.getSelectedRow();

            if (selectedRowIndex != -1) {
                String idString = model.getValueAt(selectedRowIndex, 0).toString();
                int id = Integer.parseInt(idString);

                String tef = jFormattedTextField1_Telefone.getText();
                String ddi = tef.substring(1, 3);
                String ddd = tef.substring(5, 7);
                String numero = tef.substring(7).replaceAll("[^0-9]", "");
                Telefone telefone = new Telefone(Integer.parseInt(ddi), Integer.parseInt(ddd), Integer.parseInt(numero));

                Endereco endereco;
                endereco = new Endereco(jTextField4_Logradouro.getText(), Integer.parseInt(jTextField5_Numero.getText()), jTextField6_Complemento.getText(), jFormattedTextField2_Cep.getText(), jTextField8_Cidade.getText(), jTextField9_Estado.getText());

                Contato contato;
                contato = new Contato(jTextField1_Nome.getText().toUpperCase(), telefone, jTextField3_Email.getText(), endereco);
                contato.setId(id);

                ContatoDao dao = new ContatoDao();
                ContatoControl contatoControl = new ContatoControl(dao);

                contatoControl.alterar(contato);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um contato para alterar (Para isso, liste e selecione o contato a alterar. Caso não encontre, use a busca).", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        try {
            String tef = jFormattedTextField1_Telefone.getText();
            String ddi = tef.substring(1, 3);
            String ddd = tef.substring(5, 7);
            String numero = tef.substring(7).replaceAll("[^0-9]", "");
            Telefone telefone = new Telefone(Integer.parseInt(ddi), Integer.parseInt(ddd), Integer.parseInt(numero));
            String cepText = jFormattedTextField2_Cep.getText();
            Endereco endereco;

            endereco = new Endereco(jTextField4_Logradouro.getText(), Integer.parseInt(jTextField5_Numero.getText()), jTextField6_Complemento.getText(), cepText, jTextField8_Cidade.getText(), jTextField9_Estado.getText());

            Contato contato;

            contato = new Contato(jTextField1_Nome.getText().toUpperCase(), telefone, jTextField3_Email.getText(), endereco);

            ContatoDao dao = new ContatoDao();
            ContatoControl contatoControl = new ContatoControl(dao);

            contatoControl.incluir(contato);

            //mostra caixa de texto informando se o contato foi incluido
            JOptionPane.showMessageDialog(this, "Contato incluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            //limpar os campos após a inclusão
            jTextField1_Nome.setText("");
            jTextField3_Email.setText("");
            jTextField4_Logradouro.setText("");
            jTextField5_Numero.setText("");
            jTextField6_Complemento.setText("");
            jTextField8_Cidade.setText("");
            jTextField9_Estado.setText("");
            jFormattedTextField2_Cep.setText("");
            jFormattedTextField1_Telefone.setText("");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao incluir contato: " + erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jTable_RespostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_RespostaMouseClicked
      
        DefaultTableModel model = (DefaultTableModel) jTable_Resposta.getModel();

        //seleciona a linha
        int selectedRowIndex = jTable_Resposta.getSelectedRow();

        //se a linha for selecionada...
        if (selectedRowIndex != -1) {
            try {
                //obtém os valores das colunas da linha selecionada
                String valor1 = model.getValueAt(selectedRowIndex, 1).toString();
                String valor2 = model.getValueAt(selectedRowIndex, 2).toString();
                String valor3 = model.getValueAt(selectedRowIndex, 3).toString();
                String valor4 = model.getValueAt(selectedRowIndex, 4).toString();

                //processa os valores obtidos
                String limpoValor = valor2.replaceAll("[^0-9]", "");
                String[] addressParts = valor4.split("/");
                String logradouro = addressParts[0].trim();
                String numero = addressParts[1].trim();
                String complemento = addressParts[2].trim();
                String cep = addressParts[3].replace("-", "").trim();
                String cidade = addressParts[4].trim();
                String estado = addressParts[5].trim();

                //dfine os valores nos componentes da interface
                jTextField4_Logradouro.setText(logradouro);
                jTextField5_Numero.setText(numero);
                jTextField6_Complemento.setText(complemento);
                jFormattedTextField2_Cep.setText(cep);
                jTextField9_Estado.setText(estado);
                jTextField8_Cidade.setText(cidade);
                jTextField1_Nome.setText(valor1);
                jFormattedTextField1_Telefone.setText(limpoValor);
                jTextField3_Email.setText(valor3);
            } catch (ArrayIndexOutOfBoundsException | NullPointerException | NumberFormatException | StringIndexOutOfBoundsException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao obter valores da tabela, reinicie o programa: " + ex.getMessage(), "Reinicie o programa", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTable_RespostaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6_PDF;
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Consultar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JButton jButton_Listar;
    private javax.swing.JButton jButton_ordenar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_Ordenar;
    private javax.swing.JFormattedTextField jFormattedTextField1_Telefone;
    private javax.swing.JFormattedTextField jFormattedTextField1_consultar;
    private javax.swing.JFormattedTextField jFormattedTextField2_Cep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Resposta;
    private javax.swing.JTextField jTextField1_Nome;
    private javax.swing.JTextField jTextField3_Email;
    private javax.swing.JTextField jTextField4_Logradouro;
    private javax.swing.JTextField jTextField5_Numero;
    private javax.swing.JTextField jTextField6_Complemento;
    private javax.swing.JTextField jTextField8_Cidade;
    private javax.swing.JTextField jTextField9_Estado;
    // End of variables declaration//GEN-END:variables
}
